/* tslint:disable */
/* eslint-disable */
/**
 * Form builder api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface AddFormCommand
 */
export interface AddFormCommand {
    /**
     * 
     * @type {string}
     * @memberof AddFormCommand
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddFormCommand
     */
    content?: string | null;
}
/**
 * 
 * @export
 * @interface AddResultCommand
 */
export interface AddResultCommand {
    /**
     * 
     * @type {string}
     * @memberof AddResultCommand
     */
    formId?: string;
    /**
     * 
     * @type {string}
     * @memberof AddResultCommand
     */
    content?: string | null;
}
/**
 * 
 * @export
 * @interface ErrorModel
 */
export interface ErrorModel {
    /**
     * 
     * @type {string}
     * @memberof ErrorModel
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ErrorModel
     */
    code?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ErrorModel
     */
    reference?: string | null;
    /**
     * 
     * @type {Array<ErrorModel>}
     * @memberof ErrorModel
     */
    innerErrors?: Array<ErrorModel> | null;
}
/**
 * 
 * @export
 * @interface ErrorModelApiResponseModel
 */
export interface ErrorModelApiResponseModel {
    /**
     * 
     * @type {number}
     * @memberof ErrorModelApiResponseModel
     */
    statusCode?: number;
    /**
     * 
     * @type {string}
     * @memberof ErrorModelApiResponseModel
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ErrorModelApiResponseModel
     */
    instance?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ErrorModelApiResponseModel
     */
    path?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ErrorModelApiResponseModel
     */
    method?: string | null;
    /**
     * 
     * @type {ErrorModel}
     * @memberof ErrorModelApiResponseModel
     */
    data?: ErrorModel;
}
/**
 * 
 * @export
 * @interface FormModel
 */
export interface FormModel {
    /**
     * 
     * @type {string}
     * @memberof FormModel
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof FormModel
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FormModel
     */
    content?: string | null;
}
/**
 * 
 * @export
 * @interface FormModelPagedModel
 */
export interface FormModelPagedModel {
    /**
     * 
     * @type {number}
     * @memberof FormModelPagedModel
     */
    currentPage?: number;
    /**
     * 
     * @type {number}
     * @memberof FormModelPagedModel
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof FormModelPagedModel
     */
    totalItems?: number;
    /**
     * 
     * @type {number}
     * @memberof FormModelPagedModel
     */
    totalPages?: number;
    /**
     * 
     * @type {Array<FormModel>}
     * @memberof FormModelPagedModel
     */
    items?: Array<FormModel> | null;
}
/**
 * 
 * @export
 * @interface ResultModel
 */
export interface ResultModel {
    /**
     * 
     * @type {string}
     * @memberof ResultModel
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ResultModel
     */
    formId?: string;
    /**
     * 
     * @type {string}
     * @memberof ResultModel
     */
    content?: string | null;
    /**
     * 
     * @type {FormModel}
     * @memberof ResultModel
     */
    form?: FormModel;
}
/**
 * 
 * @export
 * @interface ResultModelPagedModel
 */
export interface ResultModelPagedModel {
    /**
     * 
     * @type {number}
     * @memberof ResultModelPagedModel
     */
    currentPage?: number;
    /**
     * 
     * @type {number}
     * @memberof ResultModelPagedModel
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof ResultModelPagedModel
     */
    totalItems?: number;
    /**
     * 
     * @type {number}
     * @memberof ResultModelPagedModel
     */
    totalPages?: number;
    /**
     * 
     * @type {Array<ResultModel>}
     * @memberof ResultModelPagedModel
     */
    items?: Array<ResultModel> | null;
}
/**
 * 
 * @export
 * @interface UpdateFormCommand
 */
export interface UpdateFormCommand {
    /**
     * 
     * @type {string}
     * @memberof UpdateFormCommand
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateFormCommand
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateFormCommand
     */
    content?: string | null;
}
/**
 * 
 * @export
 * @interface WeatherForecast
 */
export interface WeatherForecast {
    /**
     * 
     * @type {string}
     * @memberof WeatherForecast
     */
    date?: string;
    /**
     * 
     * @type {number}
     * @memberof WeatherForecast
     */
    temperatureC?: number;
    /**
     * 
     * @type {string}
     * @memberof WeatherForecast
     */
    summary?: string | null;
}

/**
 * FormsApi - axios parameter creator
 * @export
 */
export const FormsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {AddFormCommand} [addFormCommand] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiv10FormsAddForm: async (addFormCommand?: AddFormCommand, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/Forms`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(addFormCommand, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiv10FormsDeleteForm: async (id: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiv10FormsDeleteForm', 'id', id)
            const localVarPath = `/api/v1/Forms/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiv10FormsGetFormById: async (id: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiv10FormsGetFormById', 'id', id)
            const localVarPath = `/api/v1/Forms/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} [page] 
         * @param {number} [limit] 
         * @param {string} [keyword] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiv10FormsGetForms: async (page?: number, limit?: number, keyword?: string, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/Forms`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['Page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['Limit'] = limit;
            }

            if (keyword !== undefined) {
                localVarQueryParameter['Keyword'] = keyword;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {UpdateFormCommand} [updateFormCommand] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiv10FormsUpdateForm: async (updateFormCommand?: UpdateFormCommand, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/Forms`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateFormCommand, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FormsApi - functional programming interface
 * @export
 */
export const FormsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FormsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {AddFormCommand} [addFormCommand] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiv10FormsAddForm(addFormCommand?: AddFormCommand, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FormModel>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiv10FormsAddForm(addFormCommand, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiv10FormsDeleteForm(id: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiv10FormsDeleteForm(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiv10FormsGetFormById(id: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FormModel>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiv10FormsGetFormById(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {number} [page] 
         * @param {number} [limit] 
         * @param {string} [keyword] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiv10FormsGetForms(page?: number, limit?: number, keyword?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FormModelPagedModel>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiv10FormsGetForms(page, limit, keyword, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {UpdateFormCommand} [updateFormCommand] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiv10FormsUpdateForm(updateFormCommand?: UpdateFormCommand, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FormModel>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiv10FormsUpdateForm(updateFormCommand, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * FormsApi - factory interface
 * @export
 */
export const FormsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FormsApiFp(configuration)
    return {
        /**
         * 
         * @param {AddFormCommand} [addFormCommand] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiv10FormsAddForm(addFormCommand?: AddFormCommand, options?: any): AxiosPromise<FormModel> {
            return localVarFp.apiv10FormsAddForm(addFormCommand, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiv10FormsDeleteForm(id: string, options?: any): AxiosPromise<void> {
            return localVarFp.apiv10FormsDeleteForm(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiv10FormsGetFormById(id: string, options?: any): AxiosPromise<FormModel> {
            return localVarFp.apiv10FormsGetFormById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} [page] 
         * @param {number} [limit] 
         * @param {string} [keyword] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiv10FormsGetForms(page?: number, limit?: number, keyword?: string, options?: any): AxiosPromise<FormModelPagedModel> {
            return localVarFp.apiv10FormsGetForms(page, limit, keyword, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {UpdateFormCommand} [updateFormCommand] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiv10FormsUpdateForm(updateFormCommand?: UpdateFormCommand, options?: any): AxiosPromise<FormModel> {
            return localVarFp.apiv10FormsUpdateForm(updateFormCommand, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for apiv10FormsAddForm operation in FormsApi.
 * @export
 * @interface FormsApiApiv10FormsAddFormRequest
 */
export interface FormsApiApiv10FormsAddFormRequest {
    /**
     * 
     * @type {AddFormCommand}
     * @memberof FormsApiApiv10FormsAddForm
     */
    readonly addFormCommand?: AddFormCommand
}

/**
 * Request parameters for apiv10FormsDeleteForm operation in FormsApi.
 * @export
 * @interface FormsApiApiv10FormsDeleteFormRequest
 */
export interface FormsApiApiv10FormsDeleteFormRequest {
    /**
     * 
     * @type {string}
     * @memberof FormsApiApiv10FormsDeleteForm
     */
    readonly id: string
}

/**
 * Request parameters for apiv10FormsGetFormById operation in FormsApi.
 * @export
 * @interface FormsApiApiv10FormsGetFormByIdRequest
 */
export interface FormsApiApiv10FormsGetFormByIdRequest {
    /**
     * 
     * @type {string}
     * @memberof FormsApiApiv10FormsGetFormById
     */
    readonly id: string
}

/**
 * Request parameters for apiv10FormsGetForms operation in FormsApi.
 * @export
 * @interface FormsApiApiv10FormsGetFormsRequest
 */
export interface FormsApiApiv10FormsGetFormsRequest {
    /**
     * 
     * @type {number}
     * @memberof FormsApiApiv10FormsGetForms
     */
    readonly page?: number

    /**
     * 
     * @type {number}
     * @memberof FormsApiApiv10FormsGetForms
     */
    readonly limit?: number

    /**
     * 
     * @type {string}
     * @memberof FormsApiApiv10FormsGetForms
     */
    readonly keyword?: string
}

/**
 * Request parameters for apiv10FormsUpdateForm operation in FormsApi.
 * @export
 * @interface FormsApiApiv10FormsUpdateFormRequest
 */
export interface FormsApiApiv10FormsUpdateFormRequest {
    /**
     * 
     * @type {UpdateFormCommand}
     * @memberof FormsApiApiv10FormsUpdateForm
     */
    readonly updateFormCommand?: UpdateFormCommand
}

/**
 * FormsApi - object-oriented interface
 * @export
 * @class FormsApi
 * @extends {BaseAPI}
 */
export class FormsApi extends BaseAPI {
    /**
     * 
     * @param {FormsApiApiv10FormsAddFormRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FormsApi
     */
    public apiv10FormsAddForm(requestParameters: FormsApiApiv10FormsAddFormRequest = {}, options?: any) {
        return FormsApiFp(this.configuration).apiv10FormsAddForm(requestParameters.addFormCommand, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {FormsApiApiv10FormsDeleteFormRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FormsApi
     */
    public apiv10FormsDeleteForm(requestParameters: FormsApiApiv10FormsDeleteFormRequest, options?: any) {
        return FormsApiFp(this.configuration).apiv10FormsDeleteForm(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {FormsApiApiv10FormsGetFormByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FormsApi
     */
    public apiv10FormsGetFormById(requestParameters: FormsApiApiv10FormsGetFormByIdRequest, options?: any) {
        return FormsApiFp(this.configuration).apiv10FormsGetFormById(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {FormsApiApiv10FormsGetFormsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FormsApi
     */
    public apiv10FormsGetForms(requestParameters: FormsApiApiv10FormsGetFormsRequest = {}, options?: any) {
        return FormsApiFp(this.configuration).apiv10FormsGetForms(requestParameters.page, requestParameters.limit, requestParameters.keyword, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {FormsApiApiv10FormsUpdateFormRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FormsApi
     */
    public apiv10FormsUpdateForm(requestParameters: FormsApiApiv10FormsUpdateFormRequest = {}, options?: any) {
        return FormsApiFp(this.configuration).apiv10FormsUpdateForm(requestParameters.updateFormCommand, options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * ResultsApi - axios parameter creator
 * @export
 */
export const ResultsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {AddResultCommand} [addResultCommand] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiv10ResultsAddResult: async (addResultCommand?: AddResultCommand, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/Results`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(addResultCommand, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiv10ResultsGetResultById: async (id: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiv10ResultsGetResultById', 'id', id)
            const localVarPath = `/api/v1/Results/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} [page] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiv10ResultsGetResults: async (page?: number, limit?: number, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/Results`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['Page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['Limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ResultsApi - functional programming interface
 * @export
 */
export const ResultsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ResultsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {AddResultCommand} [addResultCommand] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiv10ResultsAddResult(addResultCommand?: AddResultCommand, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultModel>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiv10ResultsAddResult(addResultCommand, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiv10ResultsGetResultById(id: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultModel>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiv10ResultsGetResultById(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {number} [page] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiv10ResultsGetResults(page?: number, limit?: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultModelPagedModel>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiv10ResultsGetResults(page, limit, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ResultsApi - factory interface
 * @export
 */
export const ResultsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ResultsApiFp(configuration)
    return {
        /**
         * 
         * @param {AddResultCommand} [addResultCommand] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiv10ResultsAddResult(addResultCommand?: AddResultCommand, options?: any): AxiosPromise<ResultModel> {
            return localVarFp.apiv10ResultsAddResult(addResultCommand, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiv10ResultsGetResultById(id: string, options?: any): AxiosPromise<ResultModel> {
            return localVarFp.apiv10ResultsGetResultById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} [page] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiv10ResultsGetResults(page?: number, limit?: number, options?: any): AxiosPromise<ResultModelPagedModel> {
            return localVarFp.apiv10ResultsGetResults(page, limit, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for apiv10ResultsAddResult operation in ResultsApi.
 * @export
 * @interface ResultsApiApiv10ResultsAddResultRequest
 */
export interface ResultsApiApiv10ResultsAddResultRequest {
    /**
     * 
     * @type {AddResultCommand}
     * @memberof ResultsApiApiv10ResultsAddResult
     */
    readonly addResultCommand?: AddResultCommand
}

/**
 * Request parameters for apiv10ResultsGetResultById operation in ResultsApi.
 * @export
 * @interface ResultsApiApiv10ResultsGetResultByIdRequest
 */
export interface ResultsApiApiv10ResultsGetResultByIdRequest {
    /**
     * 
     * @type {string}
     * @memberof ResultsApiApiv10ResultsGetResultById
     */
    readonly id: string
}

/**
 * Request parameters for apiv10ResultsGetResults operation in ResultsApi.
 * @export
 * @interface ResultsApiApiv10ResultsGetResultsRequest
 */
export interface ResultsApiApiv10ResultsGetResultsRequest {
    /**
     * 
     * @type {number}
     * @memberof ResultsApiApiv10ResultsGetResults
     */
    readonly page?: number

    /**
     * 
     * @type {number}
     * @memberof ResultsApiApiv10ResultsGetResults
     */
    readonly limit?: number
}

/**
 * ResultsApi - object-oriented interface
 * @export
 * @class ResultsApi
 * @extends {BaseAPI}
 */
export class ResultsApi extends BaseAPI {
    /**
     * 
     * @param {ResultsApiApiv10ResultsAddResultRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ResultsApi
     */
    public apiv10ResultsAddResult(requestParameters: ResultsApiApiv10ResultsAddResultRequest = {}, options?: any) {
        return ResultsApiFp(this.configuration).apiv10ResultsAddResult(requestParameters.addResultCommand, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ResultsApiApiv10ResultsGetResultByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ResultsApi
     */
    public apiv10ResultsGetResultById(requestParameters: ResultsApiApiv10ResultsGetResultByIdRequest, options?: any) {
        return ResultsApiFp(this.configuration).apiv10ResultsGetResultById(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ResultsApiApiv10ResultsGetResultsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ResultsApi
     */
    public apiv10ResultsGetResults(requestParameters: ResultsApiApiv10ResultsGetResultsRequest = {}, options?: any) {
        return ResultsApiFp(this.configuration).apiv10ResultsGetResults(requestParameters.page, requestParameters.limit, options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * WeatherForecastApi - axios parameter creator
 * @export
 */
export const WeatherForecastApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiv10WeatherForecastGet: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/WeatherForecast`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WeatherForecastApi - functional programming interface
 * @export
 */
export const WeatherForecastApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = WeatherForecastApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiv10WeatherForecastGet(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<WeatherForecast>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiv10WeatherForecastGet(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * WeatherForecastApi - factory interface
 * @export
 */
export const WeatherForecastApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = WeatherForecastApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiv10WeatherForecastGet(options?: any): AxiosPromise<Array<WeatherForecast>> {
            return localVarFp.apiv10WeatherForecastGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WeatherForecastApi - object-oriented interface
 * @export
 * @class WeatherForecastApi
 * @extends {BaseAPI}
 */
export class WeatherForecastApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeatherForecastApi
     */
    public apiv10WeatherForecastGet(options?: any) {
        return WeatherForecastApiFp(this.configuration).apiv10WeatherForecastGet(options).then((request) => request(this.axios, this.basePath));
    }
}


